apiVersion: v1
kind: PersistentVolumeClaim #not an actual instance of storage
metadata:
  name: data-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce #Can be used by a single node
  resources:
    requests:
      storage: 2Gi #find a 2G storage

#StorageClassName will be default, no need to set it up

# Three Access mode:
# - ReadWriteOnce: Can be used by a single node
# - ReadOnlyMany: Multipe nodes can read
# -  ReadWriteMany: Can be read and written to by many nodes